spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 112191486341-ihqa962ajv7b7bdp7au2vvs4vl8aptt3.apps.googleusercontent.com
            client-secret: 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
