# Generated by Django 2.1.15 on 2020-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201015_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_date',
        ),
        migrations.AddField(
            model_name='user',
            name='is_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
